apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-repo
data:
  branch: main
  host: github.com
  protocol: https
  repo: squad2_gitops_repo
  org: cloud-native-garage-method-cohort
  parentdir: bash -c 'echo qa/$(basename ${NAMESPACE} -dev)'
