apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  name: kspfs
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: squad2-app
    weight: 100
  wildcardPolicy: None